
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: image
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER}
      #- IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://fileserver.infra.top}
      # Default values for JDK11
      - IMAGE_ARG_GCCLIBS_VERSION=${IMAGE_ARG_GCCLIBS_VERSION:-8.2.1+20181127-1}
      - IMAGE_ARG_GLIBC_VERSION=${IMAGE_ARG_GLIBC_VERSION:-2.29-r0}
      - IMAGE_ARG_ZLIB1_VERSION=${IMAGE_ARG_ZLIB1_VERSION:-1.2.11-3}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-glibc}:${IMAGE_TAG:-2.29-r0-alpine-3.9}
  #docker-compose build dumper
  dumper:
    build:
      context: dumper
      dockerfile: Dockerfile_dumper
    image: tmp/dumper:latest
  #docker-compose build archive
  archive:
    build:
      context: .
      dockerfile: Dockerfile_archive
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-glibc}:${IMAGE_TAG:-2.29-r0-alpine-3.9}-archive
