
FROM alpine:3.7

MAINTAINER haolun


ARG IMAGE_ARG_ALPINE_MIRROR
ARG IMAGE_ARG_FILESERVER

ARG IMAGE_ARG_GCCLIBS_VERSION
ARG IMAGE_ARG_GLIBC_VERSION
ARG IMAGE_ARG_ZLIB1_VERSION


ENV ARIA2C_DOWNLOAD aria2c --file-allocation=none -c -x 10 -s 10 -m 0 --console-log-level=notice --log-level=notice --summary-interval=0


RUN set -ex \
    && echo ===== Install tools ===== \
    && echo "http://${IMAGE_ARG_ALPINE_MIRROR:-dl-cdn.alpinelinux.org}/alpine/v3.7/main" > /etc/apk/repositories \
    && echo "http://${IMAGE_ARG_ALPINE_MIRROR:-dl-cdn.alpinelinux.org}/alpine/v3.7/community" >> /etc/apk/repositories \
    && echo "http://${IMAGE_ARG_ALPINE_MIRROR:-dl-cdn.alpinelinux.org}/alpine/edge/testing/" >> /etc/apk/repositories \
    && apk add --update aria2 binutils libstdc++ \
    && rm -rf /tmp/* /var/cache/apk/*

RUN set -ex \
    && echo ===== Install glibc ===== \
    && ${ARIA2C_DOWNLOAD} -d /tmp -o "glibc-${IMAGE_ARG_GLIBC_VERSION:-2.23-r3}.apk" "${IMAGE_ARG_FILESERVER:-https://github.com}/sgerrand/alpine-pkg-glibc/releases/download/${IMAGE_ARG_GLIBC_VERSION:-2.23-r3}/glibc-${IMAGE_ARG_GLIBC_VERSION:-2.23-r3}.apk" \
    && apk add --allow-untrusted /tmp/glibc-${IMAGE_ARG_GLIBC_VERSION:-2.23-r3}.apk \
    && if [ -n "${IMAGE_ARG_GCCLIBS_VERSION}" ]; then \
           echo ===== Install archlinux gcc-libs  =====; \
           echo "https://www.archlinux.org/packages/core/x86_64/gcc-libs/gcc-libs-${IMAGE_ARG_GCCLIBS_VERSION:-7.3.1+20180406-1}-x86_64.pkg.tar.xz"; \
           echo "http://archlinux.thaller.ws/core/os/x86_64/gcc-libs-${IMAGE_ARG_GCCLIBS_VERSION:-7.3.1+20180406-1}-x86_64.pkg.tar.xz"; \
           ${ARIA2C_DOWNLOAD} -d /tmp -o "gcc-libs.tar.xz" "${IMAGE_ARG_FILESERVER:-http://archlinux.thaller.ws}/core/os/x86_64/gcc-libs-${IMAGE_ARG_GCCLIBS_VERSION:-7.3.1+20180406-1}-x86_64.pkg.tar.xz"; \
           mkdir /tmp/gcc && tar -xf /tmp/gcc-libs.tar.xz -C /tmp/gcc; \
           mv /tmp/gcc/usr/lib/libgcc* /tmp/gcc/usr/lib/libstdc++* /usr/glibc-compat/lib; \
           strip /usr/glibc-compat/lib/libgcc_s.so.* /usr/glibc-compat/lib/libstdc++.so*; \
           apk del binutils; \
       fi \
    && if [ -n "${IMAGE_ARG_ZLIB1_VERSION}" ]; then \
           echo ===== Install archlinux zlib  =====; \
           echo "https://www.archlinux.org/packages/core/x86_64/zlib/download"; \
           echo "http://archlinux.thaller.ws/core/os/x86_64/zlib-1:${IMAGE_ARG_ZLIB1_VERSION:-1.2.11-2}-x86_64.pkg.tar.xz"; \
           ${ARIA2C_DOWNLOAD} -d /tmp -o "zlib.tar.xz" "${IMAGE_ARG_FILESERVER:-http://archlinux.thaller.ws}/core/os/x86_64/zlib-1:${IMAGE_ARG_ZLIB1_VERSION:-1.2.11-2}-x86_64.pkg.tar.xz"; \
           mkdir /tmp/zlib && tar -xf /tmp/zlib.tar.xz -C /tmp/zlib; \
           mv /tmp/zlib/usr/lib/* /usr/glibc-compat/lib; \
       fi \
    && rm -rf /etc/apk/* /tmp/* /var/cache/apk/*
#    && rm -rf /lib/apk/db
