
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: image
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER}
      #- IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://fileserver.infra.top}
      # Default values for JDK8
      #- IMAGE_ARG_GCCLIBS_VERSION=${IMAGE_ARG_GCCLIBS_VERSION}
      #- IMAGE_ARG_GLIBC_VERSION=${IMAGE_ARG_GLIBC_VERSION:-2.23-r3}
      #- IMAGE_ARG_ZLIB1_VERSION=${IMAGE_ARG_ZLIB1_VERSION}
      # Default values for JDK9
      - IMAGE_ARG_GCCLIBS_VERSION=${IMAGE_ARG_GCCLIBS_VERSION}
      - IMAGE_ARG_GLIBC_VERSION=${IMAGE_ARG_GLIBC_VERSION:-2.25-r0}
      - IMAGE_ARG_ZLIB1_VERSION=${IMAGE_ARG_ZLIB1_VERSION}
    image: ${IMAGE_PREFIX:-cirepi}/${IMAGE_NAME:-glibc}:${IMAGE_TAG:-2.25-r0-alpine-3.8}
  #docker-compose build dumper
  dumper:
    build:
      context: dumper
      dockerfile: Dockerfile_dumper
    image: tmp/dumper:latest
  #docker-compose build archive
  archive:
    build:
      context: .
      dockerfile: Dockerfile_archive
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-glibc}:${IMAGE_TAG:-2.25-r0-alpine-3.8}-archive
